"""fea_export.py - parametric 2D FEA model generators for the
verification ladder: FEMM heat-flow Lua scripts and COMSOL
Multiphysics Java model files, four cases from basic to sophisticated.

Division of labour (stated in every file header): FEMM and COMSOL
heat transfer solve CONDUCTION; the oil and water films enter as
convection boundary coefficients h with bulk temperatures - the same
h the app computes from its correlations for the chosen operating
point. The FEA therefore independently checks what the app
approximates inside the solid (anisotropic core gradient, fin and
plate efficiency, wall conduction, 2D spreading), while the film
values remain visible, named parameters you can vary in either tool.

Cases:
  1 cell_axi    heated cell, axisymmetric r-z, anisotropic core
  2 fin_axi     one annular fin on a tube, axisymmetric
  3 plate_2d    plate hanging from a tube, planar (per metre depth)
  4 unit_2d     serpentine unit cell: cell + plate + tube, planar

FEMM notes: heat-flow document (type 2), Lua 4 dialect (FEMM embeds
Lua 4.0: use format(), openfile/write/closefile). Boundary property
format 2 = convection (h, Tinf). Post-processing uses unambiguous
point probes plus a heat-flux line integral; the app's predictions
are written next to each probe.

COMSOL notes: Java model file for COMSOL 6.x. Run with
  comsolbatch -inputfile <name>.java
(compiles automatically) or compile then open the saved .mph in the
GUI. All inputs live in model.param(); results include an Evaluation
Group with the FEA values, the app's predictions, and the deltas.
"""
import math

DISCLAIMER = (
    "Generated by Immersion Pack Lab. Films are parameters, not "
    "solved: h values come from the app's correlations at the chosen "
    "operating point so the FEA checks the conduction physics "
    "independently.")


# ------------------------------------------------------------------ #
#  small text helpers                                                 #
# ------------------------------------------------------------------ #
def _lua_rect(x1, y1, x2, y2):
    """Rectangle from four hi_drawline calls (works in every FEMM)."""
    return (f"hi_drawline({x1:.6g},{y1:.6g},{x2:.6g},{y1:.6g})\n"
            f"hi_drawline({x2:.6g},{y1:.6g},{x2:.6g},{y2:.6g})\n"
            f"hi_drawline({x2:.6g},{y2:.6g},{x1:.6g},{y2:.6g})\n"
            f"hi_drawline({x1:.6g},{y2:.6g},{x1:.6g},{y1:.6g})\n")


def _lua_circle(xc, yc, r):
    """Full circle as two 180-degree arcs."""
    return (f"hi_drawarc({xc + r:.6g},{yc:.6g},{xc - r:.6g},{yc:.6g},180,1)\n"
            f"hi_drawarc({xc - r:.6g},{yc:.6g},{xc + r:.6g},{yc:.6g},180,1)\n")


def _lua_head(title, axi, depth_mm, params, preds):
    p = "\n".join(
        f"{k} = {v:.6g}" if isinstance(v, (int, float)) else
        f"-- {k}: {v}" for k, v in params.items())
    pr = "\n".join(f"-- app predicts {k} = {v}" for k, v in preds.items())
    return f"""-- {title}
-- {DISCLAIMER}
-- FEMM 4.2 heat-flow problem. Open FEMM, then File > Open Lua Script.
-- All dimensions in millimetres. Lua 4 dialect (FEMM's built-in).

{pr}

-- ---------------- parameters (edit freely) ----------------
{p}

newdocument(2)                         -- 2 = heat flow problem
hi_probdef("millimeters","{'axi' if axi else 'planar'}",1e-8,{depth_mm:.6g},30)
"""


def _lua_tail(probes, flux_contour, outfile):
    """Solve + unambiguous point probes + one flux line integral,
    written to a text file and shown in a message box."""
    pb = "\n".join(
        f'T_{i} = ho_getpointvalues({x:.6g},{y:.6g})\n'
        f'line = line.."{label}: "..format("%.2f",T_{i}).." C  '
        f'(app: {app})\\n"'
        for i, (x, y, label, app) in enumerate(probes))
    fc = ""
    if flux_contour:
        pts = "\n".join(f"ho_addcontour({x:.6g},{y:.6g})"
                        for x, y in flux_contour["pts"])
        fc = f"""
ho_clearcontour()
{pts}
flux = ho_lineintegral(1)      -- heat flux through the contour, W
line = line.."{flux_contour['label']}: "..format("%.3f",flux).." W  (app: {flux_contour['app']})\\n"
ho_clearcontour()
"""
    return f"""
hi_zoomnatural()
hi_saveas("{outfile}.feh")
hi_analyze(0)
hi_loadsolution()

-- ---------------- post-processing ----------------
line = "{outfile} results\\n"
{pb}
{fc}
handle = openfile("{outfile}_results.txt","w")
write(handle, line)
closefile(handle)
messagebox(line)
ho_showdensityplot(1,0,2,0,0)   -- filled temperature plot (auto range)
"""


# ================================================================== #
#  CASE 1 - heated cell, axisymmetric                                 #
# ================================================================== #
def femm_cell_axi(P):
    """P: Q, D, H, k_r, k_z, h_side, h_end, T_oil, T_s_app,
    T_core_app, can_on, t_can, k_can."""
    R = P["D"] / 2 * 1000
    H = P["H"] * 1000
    tc = P["t_can"] * 1000 if P["can_on"] else 0.0
    qv = P["Q"] / (math.pi * (P["D"] / 2) ** 2 * P["H"])  # W/m3
    params = dict(R_mm=R, H_mm=H, Q_W=P["Q"], qv_Wm3=qv,
                  k_r=P["k_r"], k_z=P["k_z"], h_side=P["h_side"],
                  h_end=P["h_end"], T_oil=P["T_oil"])
    preds = {"can surface (mean)": f"{P['T_s_app']:.2f} C",
             "core peak": f"{P['T_core_app']:.2f} C"}
    s = _lua_head("Case 1 - heated cell in oil (axisymmetric r-z)",
                  True, 1, params, preds)
    s += f"""
-- jelly-roll core: anisotropic k, uniform volumetric heat
hi_addmaterial("core",{P['k_r']:.6g},{P['k_z']:.6g},{qv:.6g},0)
"""
    core_R = R - tc
    s += _lua_rect(0, 0, core_R, H)
    if P["can_on"]:
        s += f'hi_addmaterial("can",{P["k_can"]:.6g},{P["k_can"]:.6g},0,0)\n'
        s += _lua_rect(core_R, 0, R, H)
        s += f"""hi_addblocklabel({core_R + tc/2:.6g},{H/2:.6g})
hi_selectlabel({core_R + tc/2:.6g},{H/2:.6g})
hi_setblockprop("can",1,0,0)
hi_clearselected()
"""
    s += f"""hi_addblocklabel({core_R/2:.6g},{H/2:.6g})
hi_selectlabel({core_R/2:.6g},{H/2:.6g})
hi_setblockprop("core",1,0,0)
hi_clearselected()

-- convection on the wetted can side and (optionally) the ends
hi_addboundprop("oil_side",2,0,0,{P['T_oil']:.6g},{P['h_side']:.6g},0)
hi_addboundprop("oil_end",2,0,0,{P['T_oil']:.6g},{P['h_end']:.6g},0)
hi_addboundprop("adiabatic",1,0,0,0,0,0)  -- q = 0 on the axis
hi_selectsegment({R:.6g},{H/2:.6g})
hi_setsegmentprop("oil_side",0,1,0,0)
hi_clearselected()
hi_selectsegment({R/2:.6g},0)
hi_selectsegment({R/2:.6g},{H:.6g})
hi_setsegmentprop("{'oil_end' if P['h_end'] > 0 else 'adiabatic'}",0,1,0,0)
hi_clearselected()
"""
    if P["can_on"]:
        s += f"""hi_selectsegment({core_R + tc/2:.6g},0)
hi_selectsegment({core_R + tc/2:.6g},{H:.6g})
hi_setsegmentprop("{'oil_end' if P['h_end'] > 0 else 'adiabatic'}",0,1,0,0)
hi_clearselected()
"""
    probes = [(1e-4, H / 2, "core centre T", f"{P['T_core_app']:.2f} C"),
              (R - 1e-3, H / 2, "can mid-height T",
               f"{P['T_s_app']:.2f} C")]
    flux = dict(pts=[(R, -0.01), (R, H + 0.01)],
                label="heat out of the side", app=f"~{P['Q']:.2f} W"
                if P["h_end"] <= 0 else "side share of "
                f"{P['Q']:.2f} W")
    s += _lua_tail(probes, flux, "ipl_case1_cell")
    return s


# ================================================================== #
#  CASE 2 - one annular fin, axisymmetric                             #
# ================================================================== #
def femm_fin_axi(P):
    """P: d_o, t_wall, H_f, t_f, k_fin, h_oil, T_oil, h_w, T_w,
    eta_app, k_tube."""
    r_i = (P["d_o"] / 2 - P["t_wall"]) * 1000
    r_o = P["d_o"] / 2 * 1000
    r_f = r_o + P["H_f"] * 1000
    tf = P["t_f"] * 1000
    pitch = P["p_f"] * 1000
    y0, y1 = 0.0, pitch / 2          # half-pitch symmetric slice
    yf = tf / 2                      # half fin thickness at y=0 plane
    params = dict(r_in_mm=r_i, r_out_mm=r_o, r_fin_mm=r_f,
                  t_fin_mm=tf, halfpitch_mm=y1, k_fin=P["k_fin"],
                  k_tube=P["k_tube"], h_oil=P["h_oil"],
                  T_oil=P["T_oil"], h_water=P["h_w"], T_w=P["T_w"])
    preds = {"fin efficiency": f"{P['eta_app']:.3f} "
             "(tanh(mL)/mL with tip correction)"}
    s = _lua_head("Case 2 - one annular fin on the tube "
                  "(axisymmetric, half-pitch slice)", True, 1,
                  params, preds)
    s += f"""
hi_addmaterial("metal",{P['k_fin']:.6g},{P['k_fin']:.6g},0,0)
hi_addmaterial("tube",{P['k_tube']:.6g},{P['k_tube']:.6g},0,0)
-- tube wall over the half pitch
"""
    s += _lua_rect(r_i, y0, r_o, y1)
    s += "-- the fin: half thickness against the symmetry plane\n"
    s += _lua_rect(r_o, y0, r_f, yf)
    s += f"""hi_addblocklabel({(r_i + r_o)/2:.6g},{y1/2:.6g})
hi_selectlabel({(r_i + r_o)/2:.6g},{y1/2:.6g})
hi_setblockprop("tube",1,0,0)
hi_clearselected()
hi_addblocklabel({(r_o + r_f)/2:.6g},{yf/2:.6g})
hi_selectlabel({(r_o + r_f)/2:.6g},{yf/2:.6g})
hi_setblockprop("metal",1,0,0)
hi_clearselected()

hi_addboundprop("oil",2,0,0,{P['T_oil']:.6g},{P['h_oil']:.6g},0)
hi_addboundprop("water",2,0,0,{P['T_w']:.6g},{P['h_w']:.6g},0)
hi_addboundprop("sym",1,0,0,0,0,0)
-- water inside the tube
hi_selectsegment({r_i:.6g},{y1/2:.6g})
hi_setsegmentprop("water",0,1,0,0)
hi_clearselected()
-- oil on the fin faces, tip, and the bare tube between fins
hi_selectsegment({(r_o + r_f)/2:.6g},{yf:.6g})
hi_selectsegment({r_f:.6g},{yf/2:.6g})
hi_selectsegment({r_o:.6g},{(yf + y1)/2:.6g})
hi_setsegmentprop("oil",0,1,0,0)
hi_clearselected()
-- symmetry planes top and bottom
hi_selectsegment({(r_i + r_o)/2:.6g},{y1:.6g})
hi_selectsegment({(r_o + r_f)/2:.6g},0)
hi_selectsegment({(r_i + r_o)/2:.6g},0)
hi_setsegmentprop("sym",0,1,0,0)
hi_clearselected()
"""
    probes = [(r_o + 0.02, yf / 2, "fin root T", "between T_w and T_oil"),
              (r_f - 0.02, yf / 2, "fin tip T",
               "closer to T_oil as eta drops")]
    flux = dict(pts=[(r_i - 0.01, y0 - 0.01), (r_i - 0.01, y1 + 0.01)],
                label="heat to the water (per half pitch)",
                app=f"compare eta: Q_fea / (h_oil * A_fin * "
                    f"(T_oil - T_root)) vs {P['eta_app']:.3f}")
    s += _lua_tail(probes, flux, "ipl_case2_fin")
    return s


# ================================================================== #
#  CASE 3 - plate hanging from a tube, planar                         #
# ================================================================== #
def femm_plate_2d(P):
    """P: t_pl, H_pl, k_pl, h_oil, T_oil, tube_w, tube_h, t_wall,
    k_tube, h_w, T_w, eta_app, shape."""
    t = P["t_pl"] * 1000
    Hp = P["H_pl"] * 1000
    tw = P["tube_w"] * 1000
    th = P["tube_h"] * 1000
    wall = P["t_wall"] * 1000
    x0 = -t / 2
    params = dict(t_plate_mm=t, H_plate_mm=Hp, tube_w_mm=tw,
                  tube_h_mm=th, wall_mm=wall, k_plate=P["k_pl"],
                  k_tube=P["k_tube"], h_oil=P["h_oil"],
                  T_oil=P["T_oil"], h_water=P["h_w"], T_w=P["T_w"])
    preds = {"plate efficiency": f"{P['eta_app']:.3f}",
             "note": "planar problem, results are per metre of tube "
                     "run (into the page)"}
    s = _lua_head("Case 3 - plate hanging from the water tube "
                  "(planar section, per metre)", False, 1000,
                  params, preds)
    s += f"""
hi_addmaterial("plate",{P['k_pl']:.6g},{P['k_pl']:.6g},0,0)
hi_addmaterial("tube",{P['k_tube']:.6g},{P['k_tube']:.6g},0,0)
-- the plate: a thin strip hanging down from y=0
"""
    s += _lua_rect(x0, -Hp, x0 + t, 0)
    s += f"-- the tube above it: rectangular ring {tw:.1f} x {th:.1f}, wall {wall:.1f}\n"
    s += _lua_rect(-tw / 2, 0, tw / 2, th)
    s += _lua_rect(-tw / 2 + wall, wall, tw / 2 - wall, th - wall)
    s += f"""hi_addblocklabel(0,{-Hp/2:.6g})
hi_selectlabel(0,{-Hp/2:.6g})
hi_setblockprop("plate",1,0,0)
hi_clearselected()
hi_addblocklabel({-tw/2 + wall/2:.6g},{th/2:.6g})
hi_selectlabel({-tw/2 + wall/2:.6g},{th/2:.6g})
hi_setblockprop("tube",1,0,0)
hi_clearselected()
hi_addblocklabel(0,{th/2:.6g})
hi_selectlabel(0,{th/2:.6g})
hi_setblockprop("<No Mesh>",1,0,0)
hi_clearselected()

hi_addboundprop("oil",2,0,0,{P['T_oil']:.6g},{P['h_oil']:.6g},0)
hi_addboundprop("water",2,0,0,{P['T_w']:.6g},{P['h_w']:.6g},0)
-- oil on both plate faces, its lower tip, and the tube outside
hi_selectsegment({x0:.6g},{-Hp/2:.6g})
hi_selectsegment({x0 + t:.6g},{-Hp/2:.6g})
hi_selectsegment(0,{-Hp:.6g})
hi_selectsegment({-tw/2:.6g},{th/2:.6g})
hi_selectsegment({tw/2:.6g},{th/2:.6g})
hi_selectsegment(0,{th:.6g})
hi_selectsegment({(x0 + t/2 + tw/2)/1.6:.6g},0)
hi_selectsegment({-(x0 + t/2 + tw/2)/1.6:.6g},0)
hi_setsegmentprop("oil",0,1,0,0)
hi_clearselected()
-- water film on the tube bore
hi_selectsegment(0,{wall:.6g})
hi_selectsegment(0,{th - wall:.6g})
hi_selectsegment({-tw/2 + wall:.6g},{th/2:.6g})
hi_selectsegment({tw/2 - wall:.6g},{th/2:.6g})
hi_setsegmentprop("water",0,1,0,0)
hi_clearselected()
"""
    probes = [(0, -0.05, "plate root T", "sets the fin drive"),
              (0, -Hp + 0.05, "plate tip T",
               f"tip approach ratio -> eta, app {P['eta_app']:.3f}")]
    flux = dict(pts=[(-tw / 2 - 0.01, -0.01), (-tw / 2 - 0.01,
                                               th + 0.01),
                     (tw / 2 + 0.01, th + 0.01),
                     (tw / 2 + 0.01, -0.01)],
                label="heat into the water, W per metre",
                app="h_oil*(A_plate*eta + A_tube)*(T_oil - ...) "
                    "chain from the app")
    s += _lua_tail(probes, flux, "ipl_case3_plate")
    return s


# ================================================================== #
#  CASE 4 - serpentine unit cell, planar                              #
# ================================================================== #
def femm_unit_2d(P):
    """Half cell + half gap + plate + tube, planar, per metre.
    P adds: D, H_cell, k_r, k_z, Q_per_m, gap, h_cell, plus the
    case-3 keys."""
    Dc = P["D"] * 1000
    Hc = P["H_cell"] * 1000
    gap = P["gap"] * 1000
    t = P["t_pl"] * 1000
    tw = P["tube_w"] * 1000
    th = P["tube_h"] * 1000
    wall = P["t_wall"] * 1000
    x_cell0 = -(gap / 2 + Dc / 2) - Dc / 2
    x_cell1 = x_cell0 + Dc
    y_top = 0.0
    qv = P["Q_per_m"] / (P["D"] * P["H_cell"])          # W/m3 slab
    params = dict(D_cell_mm=Dc, H_cell_mm=Hc, gap_mm=gap,
                  t_plate_mm=t, tube_w_mm=tw, tube_h_mm=th,
                  wall_mm=wall,
                  qv_Wm3=qv, k_r=P["k_r"], k_z=P["k_z"],
                  h_cell=P["h_cell"], h_oil=P["h_oil"],
                  T_oil=P["T_oil"], h_water=P["h_w"], T_w=P["T_w"])
    preds = {"can surface": f"{P['T_s_app']:.2f} C",
             "core peak": f"{P['T_core_app']:.2f} C",
             "note": "cell modelled as an equivalent slab per metre; "
                     "the cylinder curvature is the app's job, the "
                     "2D field and plate path are the FEA's"}
    s = _lua_head("Case 4 - serpentine unit cell (planar section, "
                  "per metre): cell + oil gap (as films) + plate + "
                  "tube", False, 1000, params, preds)
    s += f"""
hi_addmaterial("cellslab",{P['k_r']:.6g},{P['k_z']:.6g},{qv:.6g},0)
hi_addmaterial("plate",{P['k_pl']:.6g},{P['k_pl']:.6g},0,0)
hi_addmaterial("tube",{P['k_tube']:.6g},{P['k_tube']:.6g},0,0)
-- the cell as a heat-generating slab, top at the tube-zone line
"""
    s += _lua_rect(x_cell0, -Hc, x_cell1, y_top)
    s += "-- the plate in the gap to its right, hanging from the tube\n"
    s += _lua_rect(-t / 2, -Hc, t / 2, 0)
    s += _lua_rect(-tw / 2, 0, tw / 2, th)
    s += _lua_rect(-tw / 2 + wall, wall, tw / 2 - wall, th - wall)
    s += f"""hi_addblocklabel({(x_cell0 + x_cell1)/2:.6g},{-Hc/2:.6g})
hi_selectlabel({(x_cell0 + x_cell1)/2:.6g},{-Hc/2:.6g})
hi_setblockprop("cellslab",1,0,0)
hi_clearselected()
hi_addblocklabel(0,{-Hc/2:.6g})
hi_selectlabel(0,{-Hc/2:.6g})
hi_setblockprop("plate",1,0,0)
hi_clearselected()
hi_addblocklabel({-tw/2 + wall/2:.6g},{th/2:.6g})
hi_selectlabel({-tw/2 + wall/2:.6g},{th/2:.6g})
hi_setblockprop("tube",1,0,0)
hi_clearselected()
hi_addblocklabel(0,{th/2:.6g})
hi_selectlabel(0,{th/2:.6g})
hi_setblockprop("<No Mesh>",1,0,0)
hi_clearselected()

-- films: the oil never appears as a domain, only as h and T_oil
hi_addboundprop("cellfilm",2,0,0,{P['T_oil']:.6g},{P['h_cell']:.6g},0)
hi_addboundprop("oil",2,0,0,{P['T_oil']:.6g},{P['h_oil']:.6g},0)
hi_addboundprop("water",2,0,0,{P['T_w']:.6g},{P['h_w']:.6g},0)
hi_addboundprop("sym",1,0,0,0,0,0)
-- cell faces wetted by oil
hi_selectsegment({x_cell1:.6g},{-Hc/2:.6g})
hi_selectsegment({(x_cell0 + x_cell1)/2:.6g},0)
hi_selectsegment({(x_cell0 + x_cell1)/2:.6g},{-Hc:.6g})
hi_setsegmentprop("cellfilm",0,1,0,0)
hi_clearselected()
-- symmetry on the cell's far face (mirror cell beyond)
hi_selectsegment({x_cell0:.6g},{-Hc/2:.6g})
hi_setsegmentprop("sym",0,1,0,0)
hi_clearselected()
-- plate faces, tip, tube outer
hi_selectsegment({-t/2:.6g},{-Hc/2:.6g})
hi_selectsegment({t/2:.6g},{-Hc/2:.6g})
hi_selectsegment(0,{-Hc:.6g})
hi_selectsegment({-tw/2:.6g},{th/2:.6g})
hi_selectsegment({tw/2:.6g},{th/2:.6g})
hi_selectsegment(0,{th:.6g})
hi_selectsegment({(t/2 + tw/2)/2:.6g},0)
hi_selectsegment({-(t/2 + tw/2)/2:.6g},0)
hi_setsegmentprop("oil",0,1,0,0)
hi_clearselected()
-- water bore
hi_selectsegment(0,{wall:.6g})
hi_selectsegment(0,{th - wall:.6g})
hi_selectsegment({-tw/2 + wall:.6g},{th/2:.6g})
hi_selectsegment({tw/2 - wall:.6g},{th/2:.6g})
hi_setsegmentprop("water",0,1,0,0)
hi_clearselected()
"""
    probes = [((x_cell0 + x_cell1) / 2, -Hc / 2, "cell centre",
               f"{P['T_core_app']:.2f} C"),
              (x_cell1 - 0.05, -Hc / 2, "can face",
               f"{P['T_s_app']:.2f} C"),
              (0, -0.5, "plate root", "near tube wall T"),
              (0, -Hc + 0.5, "plate tip", "approach to T_oil")]
    flux = dict(pts=[(-tw / 2 - 0.01, -0.01),
                     (-tw / 2 - 0.01, th + 0.01),
                     (tw / 2 + 0.01, th + 0.01),
                     (tw / 2 + 0.01, -0.01)],
                label="heat into the water, W per metre",
                app=f"{P['Q_per_m']:.1f} W/m generated in the cell "
                    "less what the cell film returns to the bath")
    s += _lua_tail(probes, flux, "ipl_case4_unit")
    return s


# ================================================================== #
#  COMSOL Java builders                                               #
# ================================================================== #
def _j_head(cls, title, preds):
    pr = "\n".join(f" * app predicts {k} = {v}" for k, v in preds.items())
    return f"""/*
 * {title}
 * {DISCLAIMER}
 *
{pr}
 *
 * Run:   comsolbatch -inputfile {cls}.java
 * (COMSOL compiles it, solves, writes {cls}_results.txt and saves
 *  {cls}.mph for the GUI.)  Written for the COMSOL 6.x Java API.
 */
import com.comsol.model.*;
import com.comsol.model.util.*;

public class {cls} {{
  public static Model run() {{
    Model model = ModelUtil.create("Model");
"""


def _j_params(d):
    out = ""
    for k, (v, desc) in d.items():
        out += (f'    model.param().set("{k}", "{v}", "{desc}");\n')
    return out


def _j_tail(cls, evals):
    """evals: list of (label_expr_unit tuples) -> EvalGlobal rows."""
    exprs = ", ".join(f'"{e}"' for e, _, _ in evals)
    units = ", ".join(f'"{u}"' for _, u, _ in evals)
    descs = ", ".join(f'"{d_}"' for _, _, d_ in evals)
    return f"""
    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").run();

    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr",
        new String[]{{{exprs}}});
    model.result().numerical("gev1").set("unit",
        new String[]{{{units}}});
    model.result().numerical("gev1").set("descr",
        new String[]{{{descs}}});
    model.result().table().create("tbl1", "Table");
    model.result().numerical("gev1").set("table", "tbl1");
    model.result().numerical("gev1").setResult();
    model.result().export().create("texp1", "Table");
    model.result().export("texp1").set("table", "tbl1");
    model.result().export("texp1").set("filename",
        "{cls}_results.txt");
    model.result().export("texp1").run();

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", "T");
    model.result("pg1").feature("surf1").set("unit", "degC");
    model.result("pg1").create("con1", "Contour");
    model.result("pg1").feature("con1").set("expr", "T");
    model.result("pg1").feature("con1").set("unit", "degC");

    model.save("{cls}");
    return model;
  }}

  public static void main(String[] args) {{
    run();
  }}
}}
"""


def _j_boxsel(name, dim, xmin, xmax, ymin, ymax):
    return (f'    model.component("comp1").geom("geom1").create("{name}",'
            f' "BoxSelection");\n'
            f'    model.component("comp1").geom("geom1").feature("{name}")'
            f'.set("entitydim", {dim});\n'
            + "".join(
                f'    model.component("comp1").geom("geom1").feature('
                f'"{name}").set("{k}", "{v}");\n'
                for k, v in [("xmin", xmin), ("xmax", xmax),
                             ("ymin", ymin), ("ymax", ymax)])
            + f'    model.component("comp1").geom("geom1").feature('
              f'"{name}").set("condition", "inside");\n')


def comsol_cell_axi(P):
    cls = "ipl_case1_cell"
    preds = {"can surface (mean)": f"{P['T_s_app']:.2f} degC",
             "core peak": f"{P['T_core_app']:.2f} degC"}
    s = _j_head(cls, "Case 1 - heated cell in oil (2D axisymmetric)",
                preds)
    s += _j_params({
        "D_cell": (f"{P['D']}[m]", "cell diameter"),
        "H_cell": (f"{P['H']}[m]", "cell height"),
        "Q_cell": (f"{P['Q']}[W]", "heat in the cell"),
        "k_r": (f"{P['k_r']}[W/(m*K)]", "radial jelly-roll k"),
        "k_z": (f"{P['k_z']}[W/(m*K)]", "axial jelly-roll k"),
        "h_side": (f"{P['h_side']}[W/(m^2*K)]",
                   "oil film on the can side (from the app)"),
        "h_end": (f"{P['h_end']}[W/(m^2*K)]", "oil film on the ends"),
        "T_oil": (f"{P['T_oil']}[degC]", "bulk oil"),
        "qv": ("Q_cell/(pi*(D_cell/2)^2*H_cell)",
               "volumetric heat"),
        "T_s_app": (f"{P['T_s_app']}[degC]", "app: can surface"),
        "T_core_app": (f"{P['T_core_app']}[degC]", "app: core peak"),
    })
    s += """
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1")
        .set("size", new String[]{"D_cell/2", "H_cell"});
"""
    s += _j_boxsel("selSide", 1, "D_cell/2-1e-6", "D_cell/2+1e-6",
                   "-1e-6", "H_cell+1e-6")
    s += _j_boxsel("selEnds", 1, "-1e-6", "D_cell/2+1e-6",
                   "-1e-6" if False else "-1e-6", "1e-6")
    s += _j_boxsel("selTop", 1, "-1e-6", "D_cell/2+1e-6",
                   "H_cell-1e-6", "H_cell+1e-6")
    s += """
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("thermalconductivity", new String[]{
            "k_r", "0", "0", "0", "k_r", "0", "0", "0", "k_z"});
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("density", "2500");
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("heatcapacity", "900");

    model.component("comp1").physics().create("ht", "HeatTransfer",
        "geom1");
    model.component("comp1").physics("ht").create("hs1", "HeatSource",
        2);
    model.component("comp1").physics("ht").feature("hs1").selection()
        .all();
    model.component("comp1").physics("ht").feature("hs1")
        .set("Q0", "qv");
    model.component("comp1").physics("ht").create("hf1", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf1").selection()
        .named("geom1_selSide");
    model.component("comp1").physics("ht").feature("hf1")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf1")
        .set("h", "h_side");
    model.component("comp1").physics("ht").feature("hf1")
        .set("Text", "T_oil");
    model.component("comp1").physics("ht").create("hf2", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf2").selection()
        .named("geom1_selEnds");
    model.component("comp1").physics("ht").feature("hf2")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf2")
        .set("h", "h_end");
    model.component("comp1").physics("ht").feature("hf2")
        .set("Text", "T_oil");
    model.component("comp1").physics("ht").create("hf3", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf3").selection()
        .named("geom1_selTop");
    model.component("comp1").physics("ht").feature("hf3")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf3")
        .set("h", "h_end");
    model.component("comp1").physics("ht").feature("hf3")
        .set("Text", "T_oil");

    model.component("comp1").cpl().create("maxop1", "Maximum");
    model.component("comp1").cpl("maxop1").selection().all();
    model.component("comp1").cpl().create("aveop1", "Average");
    model.component("comp1").cpl("aveop1").selection()
        .geom("geom1", 1);
    model.component("comp1").cpl("aveop1").selection()
        .named("geom1_selSide");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(3);
"""
    evals = [("maxop1(T)", "degC", "FEA core peak"),
             ("T_core_app", "degC", "app core peak"),
             ("maxop1(T)-T_core_app", "K", "delta core"),
             ("aveop1(T)", "degC", "FEA can surface mean"),
             ("T_s_app", "degC", "app can surface"),
             ("aveop1(T)-T_s_app", "K", "delta surface")]
    s += _j_tail(cls, evals)
    return s


def comsol_plate_2d(P, with_cell=False, extra=None):
    cls = "ipl_case4_unit" if with_cell else "ipl_case3_plate"
    title = ("Case 4 - serpentine unit cell (planar, per metre)"
             if with_cell else
             "Case 3 - plate hanging from the tube (planar, per "
             "metre)")
    preds = {"plate efficiency": f"{P['eta_app']:.3f}"}
    if with_cell:
        preds.update({"can surface": f"{extra['T_s_app']:.2f} degC",
                      "core peak": f"{extra['T_core_app']:.2f} degC"})
    s = _j_head(cls, title, preds)
    prm = {
        "t_pl": (f"{P['t_pl']}[m]", "plate thickness"),
        "H_pl": (f"{P['H_pl']}[m]", "plate height"),
        "k_pl": (f"{P['k_pl']}[W/(m*K)]", "plate conductivity"),
        "tube_w": (f"{P['tube_w']}[m]", "tube width"),
        "tube_h": (f"{P['tube_h']}[m]", "tube height"),
        "t_wall": (f"{P['t_wall']}[m]", "tube wall"),
        "k_tube": (f"{P['k_tube']}[W/(m*K)]", "tube conductivity"),
        "h_oil": (f"{P['h_oil']}[W/(m^2*K)]",
                  "oil film on plate and tube (from the app)"),
        "T_oil": (f"{P['T_oil']}[degC]", "bulk oil"),
        "h_w": (f"{P['h_w']}[W/(m^2*K)]", "water film (from the app)"),
        "T_w": (f"{P['T_w']}[degC]", "water mean"),
        "eta_app": (f"{P['eta_app']}", "app plate efficiency"),
    }
    if with_cell:
        prm.update({
            "D_cell": (f"{extra['D']}[m]", "cell diameter (slab width)"),
            "H_cell": (f"{extra['H_cell']}[m]", "cell height"),
            "gap": (f"{extra['gap']}[m]", "cell-to-plate oil gap"),
            "k_r": (f"{extra['k_r']}[W/(m*K)]", "cell k across"),
            "k_z": (f"{extra['k_z']}[W/(m*K)]", "cell k along"),
            "Q_per_m": (f"{extra['Q_per_m']}[W/m]",
                        "cell heat per metre of tube run"),
            "h_cell": (f"{extra['h_cell']}[W/(m^2*K)]",
                       "oil film on the can (from the app)"),
            "T_s_app": (f"{extra['T_s_app']}[degC]", "app can surface"),
            "T_core_app": (f"{extra['T_core_app']}[degC]",
                           "app core peak"),
        })
    s += _j_params(prm)
    s += """
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 2);
    // plate strip hanging below y = 0
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1")
        .set("size", new String[]{"t_pl", "H_pl"});
    model.component("comp1").geom("geom1").feature("r1")
        .set("pos", new String[]{"-t_pl/2", "-H_pl"});
    // tube ring above it
    model.component("comp1").geom("geom1").create("r2", "Rectangle");
    model.component("comp1").geom("geom1").feature("r2")
        .set("size", new String[]{"tube_w", "tube_h"});
    model.component("comp1").geom("geom1").feature("r2")
        .set("pos", new String[]{"-tube_w/2", "0"});
    model.component("comp1").geom("geom1").create("r3", "Rectangle");
    model.component("comp1").geom("geom1").feature("r3")
        .set("size", new String[]{"tube_w-2*t_wall",
                                  "tube_h-2*t_wall"});
    model.component("comp1").geom("geom1").feature("r3")
        .set("pos", new String[]{"-tube_w/2+t_wall", "t_wall"});
    model.component("comp1").geom("geom1").create("dif1",
        "Difference");
    model.component("comp1").geom("geom1").feature("dif1")
        .selection("input").set("r2");
    model.component("comp1").geom("geom1").feature("dif1")
        .selection("input2").set("r3");
"""
    if with_cell:
        s += """
    // the cell as a heat-generating slab left of the gap
    model.component("comp1").geom("geom1").create("r4", "Rectangle");
    model.component("comp1").geom("geom1").feature("r4")
        .set("size", new String[]{"D_cell", "H_cell"});
    model.component("comp1").geom("geom1").feature("r4")
        .set("pos", new String[]{"-t_pl/2-gap-D_cell", "-H_cell"});
"""
    s += _j_boxsel("selBore", 1,
                   "-tube_w/2+t_wall-1e-6", "tube_w/2-t_wall+1e-6",
                   "t_wall-1e-6", "tube_h-t_wall+1e-6")
    s += _j_boxsel("selPlate", 2, "-t_pl/2-1e-6", "t_pl/2+1e-6",
                   "-H_pl-1e-6", "1e-6")
    if with_cell:
        s += _j_boxsel("selCell", 2,
                       "-t_pl/2-gap-D_cell-1e-6", "-t_pl/2-gap+1e-6",
                       "-H_cell-1e-6", "1e-6")
        s += _j_boxsel("selCellFaces", 1,
                       "-t_pl/2-gap-D_cell-1e-6", "-t_pl/2-gap+1e-6",
                       "-H_cell-1e-6", "1e-6")
    s += """
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("matPl", "Common");
    model.component("comp1").material("matPl").propertyGroup("def")
        .set("thermalconductivity", "k_pl");
    model.component("comp1").material("matPl").propertyGroup("def")
        .set("density", "2700");
    model.component("comp1").material("matPl").propertyGroup("def")
        .set("heatcapacity", "900");
    model.component("comp1").material("matPl").selection()
        .named("geom1_selPlate");
    model.component("comp1").material().create("matTu", "Common");
    model.component("comp1").material("matTu").propertyGroup("def")
        .set("thermalconductivity", "k_tube");
    model.component("comp1").material("matTu").propertyGroup("def")
        .set("density", "8900");
    model.component("comp1").material("matTu").propertyGroup("def")
        .set("heatcapacity", "390");
    model.component("comp1").material("matTu").selection().all();
"""
    if with_cell:
        s += """
    model.component("comp1").material().create("matCe", "Common");
    model.component("comp1").material("matCe").propertyGroup("def")
        .set("thermalconductivity", new String[]{
            "k_r", "0", "0", "0", "k_z", "0", "0", "0", "k_r"});
    model.component("comp1").material("matCe").propertyGroup("def")
        .set("density", "2500");
    model.component("comp1").material("matCe").propertyGroup("def")
        .set("heatcapacity", "900");
    model.component("comp1").material("matCe").selection()
        .named("geom1_selCell");
"""
    s += """
    model.component("comp1").physics().create("ht", "HeatTransfer",
        "geom1");
"""
    if with_cell:
        s += """
    model.component("comp1").physics("ht").create("hs1", "HeatSource",
        2);
    model.component("comp1").physics("ht").feature("hs1").selection()
        .named("geom1_selCell");
    model.component("comp1").physics("ht").feature("hs1")
        .set("Q0", "Q_per_m/(D_cell*H_cell)");
    model.component("comp1").physics("ht").create("hfc", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hfc").selection()
        .named("geom1_selCellFaces");
    model.component("comp1").physics("ht").feature("hfc")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hfc")
        .set("h", "h_cell");
    model.component("comp1").physics("ht").feature("hfc")
        .set("Text", "T_oil");
"""
    s += """
    // oil on every exterior boundary...
    model.component("comp1").physics("ht").create("hf1", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf1").selection()
        .all();
    model.component("comp1").physics("ht").feature("hf1")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf1")
        .set("h", "h_oil");
    model.component("comp1").physics("ht").feature("hf1")
        .set("Text", "T_oil");
    // ...then the water bore overrides it
    model.component("comp1").physics("ht").create("hf2", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf2").selection()
        .named("geom1_selBore");
    model.component("comp1").physics("ht").feature("hf2")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf2")
        .set("h", "h_w");
    model.component("comp1").physics("ht").feature("hf2")
        .set("Text", "T_w");

    model.component("comp1").cpl().create("intB", "Integration");
    model.component("comp1").cpl("intB").selection().geom("geom1", 1);
    model.component("comp1").cpl("intB").selection()
        .named("geom1_selBore");
    model.component("comp1").cpl().create("maxop1", "Maximum");
    model.component("comp1").cpl("maxop1").selection().all();
"""
    if with_cell:
        s += """
    model.component("comp1").cpl().create("aveS", "Average");
    model.component("comp1").cpl("aveS").selection().geom("geom1", 1);
    model.component("comp1").cpl("aveS").selection()
        .named("geom1_selCellFaces");
"""
    s += """
    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(2);
"""
    evals = [("intB(ht.ntflux)", "W/m", "FEA heat into the water"),
             ("maxop1(T)", "degC", "FEA hottest point"),
             ("eta_app", "1", "app plate efficiency (compare via "
                              "flux ratio)")]
    if with_cell:
        evals += [("aveS(T)", "degC", "FEA can surface mean"),
                  ("T_s_app", "degC", "app can surface"),
                  ("aveS(T)-T_s_app", "K", "delta surface"),
                  ("T_core_app", "degC", "app core peak"),
                  ("maxop1(T)-T_core_app", "K", "delta core")]
    s += _j_tail(cls, evals)
    return s


def comsol_fin_axi(P):
    cls = "ipl_case2_fin"
    preds = {"fin efficiency": f"{P['eta_app']:.3f}"}
    s = _j_head(cls, "Case 2 - one annular fin (2D axisymmetric, "
                     "half-pitch slice)", preds)
    s += _j_params({
        "r_in": (f"{P['d_o']/2 - P['t_wall']}[m]", "tube bore radius"),
        "r_out": (f"{P['d_o']/2}[m]", "tube outer radius"),
        "H_f": (f"{P['H_f']}[m]", "fin height"),
        "t_f": (f"{P['t_f']}[m]", "fin thickness"),
        "p_f": (f"{P['p_f']}[m]", "fin pitch"),
        "k_fin": (f"{P['k_fin']}[W/(m*K)]", "fin conductivity"),
        "k_tube": (f"{P['k_tube']}[W/(m*K)]", "tube conductivity"),
        "h_oil": (f"{P['h_oil']}[W/(m^2*K)]", "oil film (from app)"),
        "T_oil": (f"{P['T_oil']}[degC]", "bulk oil"),
        "h_w": (f"{P['h_w']}[W/(m^2*K)]", "water film (from app)"),
        "T_w": (f"{P['T_w']}[degC]", "water mean"),
        "eta_app": (f"{P['eta_app']}", "app fin efficiency"),
    })
    s += """
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);
    // tube wall over the half pitch
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1")
        .set("size", new String[]{"r_out-r_in", "p_f/2"});
    model.component("comp1").geom("geom1").feature("r1")
        .set("pos", new String[]{"r_in", "0"});
    // half of one fin against the z = 0 symmetry plane
    model.component("comp1").geom("geom1").create("r2", "Rectangle");
    model.component("comp1").geom("geom1").feature("r2")
        .set("size", new String[]{"H_f", "t_f/2"});
    model.component("comp1").geom("geom1").feature("r2")
        .set("pos", new String[]{"r_out", "0"});
"""
    s += _j_boxsel("selBore", 1, "r_in-1e-7", "r_in+1e-7", "-1e-7",
                   "p_f/2+1e-7")
    s += _j_boxsel("selFin", 2, "r_out-1e-7", "r_out+H_f+1e-7",
                   "-1e-7", "t_f/2+1e-7")
    s += """
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("thermalconductivity", "k_fin");
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("density", "2700");
    model.component("comp1").material("mat1").propertyGroup("def")
        .set("heatcapacity", "900");
    model.component("comp1").material("mat1").selection().all();

    model.component("comp1").physics().create("ht", "HeatTransfer",
        "geom1");
    model.component("comp1").physics("ht").create("hf1", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf1").selection()
        .all();
    model.component("comp1").physics("ht").feature("hf1")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf1")
        .set("h", "h_oil");
    model.component("comp1").physics("ht").feature("hf1")
        .set("Text", "T_oil");
    model.component("comp1").physics("ht").create("hf2", "HeatFluxBoundary", 1);
    model.component("comp1").physics("ht").feature("hf2").selection()
        .named("geom1_selBore");
    model.component("comp1").physics("ht").feature("hf2")
        .set("HeatFluxType", "ConvectiveHeatFlux");
    model.component("comp1").physics("ht").feature("hf2")
        .set("h", "h_w");
    model.component("comp1").physics("ht").feature("hf2")
        .set("Text", "T_w");

    model.component("comp1").cpl().create("intB", "Integration");
    model.component("comp1").cpl("intB").selection().geom("geom1", 1);
    model.component("comp1").cpl("intB").selection()
        .named("geom1_selBore");
    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(2);
"""
    evals = [("intB(ht.ntflux)", "W", "FEA heat to water (half "
                                      "pitch, axisym)"),
             ("eta_app", "1", "app fin efficiency for comparison")]
    s += _j_tail(cls, evals)
    return s
