"""fea_export.py - the BASIC MODULE: one battery in a liquid tank,
plane 2D, transient, no cooling. Everything else has been removed; the
ladder rebuilds from this rung upward, together.

The model, matched to the ODYSSEV-WP3 Fluent report (18/07/2026):
a rectangular liquid tank (water in the report, selectable) with a
long HEAT BAR of square cross-section running into the plane - the
report's battery surrogate is a 5 x 5 x 300 mm aluminium bar, 10 mm
above the tank floor, generating 1e5 W/m3. Plane 2D (NOT
axisymmetric). Boundary conditions as the report: sides and bottom
adiabatic; the TOP either fixed at T_top (the report's 25 degC sink,
giving a steady state) or adiabatic (sealed, transient only). The
liquid is a conducting solid; buoyant convection is NOT solved - a
liquid effective-conductivity multiplier k_mult is provided so the
convection Fluent resolves can be emulated: the k_mult that matches
Fluent IS the Nusselt number of the internal circulation.

Built-in correctness check (why you can trust the run): with h_ext = 0
the domain conserves energy exactly, so the volume-average temperature
must follow T(t) = T0 + [Q/(sum of rho*cp*A)] * t to numerical
precision, independent of mesh. The model carries that slope as a
parameter and the Evaluation Group tabulates the deviation at every
output time. A wrong geometry, source, or material shows up there
immediately.

COMSOL only for this rung: FEMM's heat-flow solver is steady-state, so
it cannot represent an uncooled (never-steady) tank. FEMM returns at
the first steady rung.

Run:  comsolbatch -inputfile ipl_basic_2d.java
"""

DISCLAIMER = (
    "Generated by Immersion Pack Lab - basic module. Plane 2D, "
    "transient, conduction only, adiabatic outer walls (h_ext "
    "parameter, default 0).")



def _rows_geom_2d(P):
    n = int(P.get("n_rows", 1) or 1)
    out = ("    // the batteries: each row of cells seen end-on is "
           "one d-wide,\n    // h-tall rectangle; rows repeat "
           "across the width at the set pitch\n")
    for k in range(1, n + 1):
        off = f"({2*k - 1 - n}/2.0)*pitch_x"
        out += (f'    model.component("comp1").geom("geom1")'
                f'.create("r_b{k}", "Rectangle");\n'
                f'    model.component("comp1").geom("geom1")'
                f'.feature("r_b{k}")\n'
                f'        .set("size", new String[]'
                f'{{"b_w", "b_h"}});\n'
                f'    model.component("comp1").geom("geom1")'
                f'.feature("r_b{k}")\n'
                f'        .set("pos", new String[]'
                f'{{"W_tank/2 - b_w/2 + x_off + {off}",\n'
                f'                                 "gap_bot"}});\n')
    return out


def _rows_geom_3d(P):
    """REAL cells: an n_rows (across, x) by n_cells (deep, y) grid
    of vertical cylinders, radius b_w/2, height b_h, centred in
    both plan directions at pitch_x / pitch_y. Falls back to a
    single rectangular block when cyl_cells is off (custom-bar
    mode)."""
    if not P.get("cyl_cells"):
        return ('    model.component("comp1").geom("geom1")'
                '.create("blk2", "Block");\n'
                '    model.component("comp1").geom("geom1")'
                '.feature("blk2")\n'
                '        .set("size", new String[]'
                '{"b_w", "L_z", "b_h"});\n'
                '    model.component("comp1").geom("geom1")'
                '.feature("blk2")\n'
                '        .set("pos", new String[]'
                '{"W_tank/2 - b_w/2 + x_off", "0",\n'
                '                                 "gap_bot"});\n')
    nx = int(P.get("n_rows", 1) or 1)
    ny = int(P.get("n_cells", 1) or 1)
    out = (f"    // the batteries: {nx} x {ny} REAL cylindrical "
           "cells, axis vertical,\n    // centred in plan at "
           "pitch_x (across) / pitch_y (deep)\n")
    for kx in range(1, nx + 1):
        for ky in range(1, ny + 1):
            tag = f"cb{kx}_{ky}"
            ox = f"({2*kx - 1 - nx}/2.0)*pitch_x"
            oy = f"({2*ky - 1 - ny}/2.0)*pitch_y"
            out += (
                f'    model.component("comp1").geom("geom1")'
                f'.create("{tag}", "Cylinder");\n'
                f'    model.component("comp1").geom("geom1")'
                f'.feature("{tag}").set("r", "b_w/2");\n'
                f'    model.component("comp1").geom("geom1")'
                f'.feature("{tag}").set("h", "b_h");\n'
                f'    model.component("comp1").geom("geom1")'
                f'.feature("{tag}").set("pos", new String[]\n'
                f'        {{"W_tank/2 + x_off + {ox}", '
                f'"L_z/2 + {oy}", "gap_bot"}});\n')
    return out


def _settings_java(P, prm, cls):
    """Static echo of the run's parameters to {cls}_settings.txt -
    plain java.io, no COMSOL API risk. The app reads this file (or
    the .java itself) to configure the analytical model from the
    RUN, not from the current sliders."""
    lines = [f'    java.io.PrintWriter pw_ = new '
             f'java.io.PrintWriter("{cls}_settings.txt");',
             f'    pw_.println("% ipl-settings v1 cls={cls} '
             f'dim={P.get("_dim", 2)} '
             f'flow={P.get("flow_mode", "top" if P.get("top_fixed", True) else "sealed")} '
             f'cyl={1 if P.get("cyl_cells") else 0}");']
    for k, v, _ in prm:
        vv = str(v).replace('"', '')
        lines.append(f'    pw_.println("{k}={vv}");')
    if P.get("heat_mode") == "battery":
        qn = float(P.get("I_cell", 0.0)) ** 2 * (
            float(P.get("R0_cell", 0.0)) +
            float(P.get("R1_cell", 0.0)))
    else:
        qn = float(P.get("Q_cell", 0.0))
    lines.append(f'    pw_.println("Q_eval={qn}");')
    lines.append('    pw_.close();')
    return "\n".join(lines) + "\n"


def _pipe_prm_rows(P):
    if not P.get("n_pipes"):
        return []
    return [
        ("r_pipe", f"{P.get('d_pipe', 0.008)/2}[m]",
         "water-pipe outer radius"),
        ("pipe_drop", f"{P.get('pipe_drop', 0.006)}[m]",
         "pipe centre below the lid"),
        ("h_w", f"{P.get('h_w', 1500.0)}[W/(m^2*K)]",
         "water-side film on the pipe wall"),
        ("T_w", f"{P.get('T_w', 20.0)}[degC]",
         "water temperature in the pipes"),
    ]


def _pipes_geom_2d(P):
    n = int(P.get("n_pipes") or 0)
    if not n:
        return ""
    s = ("    // water pipes: circular channels subtracted from "
         "the liquid;\n    // their walls get the water-side film "
         "(h_w, T_w)\n")
    for k in range(1, n + 1):
        fx = (2 * k - 1) / (2 * n)
        s += (f'    model.component("comp1").geom("geom1")'
              f'.create("c{k}", "Circle");\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("c{k}").set("r", "r_pipe");\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("c{k}").set("pos", new String[]'
              f'{{"W_tank*{fx:.6f}", "H_tank - pipe_drop"}});\n')
    cs = ", ".join(f'"c{k}"' for k in range(1, n + 1))
    s += ('    model.component("comp1").geom("geom1")'
          '.create("dif1", "Difference");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("dif1").selection("input")\n'
          '        .set(new String[]{"r1"});\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("dif1").selection("input2")\n'
          f'        .set(new String[]{{{cs}}});\n'
          '    model.component("comp1").geom("geom1")'
          '.create("selPipes", "BoxSelection");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("entitydim", 1);\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("xmin", "1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("xmax", "W_tank - 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes")\n'
          '        .set("ymin", "H_tank - pipe_drop - r_pipe '
          '- 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes")\n'
          '        .set("ymax", "H_tank - pipe_drop + r_pipe '
          '+ 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("condition", "inside");\n')
    return s


def _pipes_geom_3d(P):
    n = int(P.get("n_pipes") or 0)
    if not n:
        return ""
    s = ("    // water pipes: cylinders along the depth, "
         "subtracted; walls get\n    // the water-side film "
         "(h_w, T_w). If 6.4 rejects axistype, use the\n"
         "    // commented cartesian axis form.\n")
    for k in range(1, n + 1):
        fx = (2 * k - 1) / (2 * n)
        s += (f'    model.component("comp1").geom("geom1")'
              f'.create("cyl{k}", "Cylinder");\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("cyl{k}").set("r", "r_pipe");\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("cyl{k}").set("h", "L_z");\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("cyl{k}").set("axistype", "y");\n'
              f'    // .set("axistype","cartesian"); '
              f'.set("ax3", new double[]{{0,1,0}});\n'
              f'    model.component("comp1").geom("geom1")'
              f'.feature("cyl{k}").set("pos", new String[]'
              f'{{"W_tank*{fx:.6f}", "0", '
              f'"H_tank - pipe_drop"}});\n')
    cs = ", ".join(f'"cyl{k}"' for k in range(1, n + 1))
    s += ('    model.component("comp1").geom("geom1")'
          '.create("dif1", "Difference");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("dif1").selection("input")\n'
          '        .set(new String[]{"blk1"});\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("dif1").selection("input2")\n'
          f'        .set(new String[]{{{cs}}});\n'
          '    model.component("comp1").geom("geom1")'
          '.create("selPipes", "BoxSelection");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("entitydim", 2);\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("xmin", "1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("xmax", "W_tank - 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes")\n'
          '        .set("zmin", "H_tank - pipe_drop - r_pipe '
          '- 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes")\n'
          '        .set("zmax", "H_tank - pipe_drop + r_pipe '
          '+ 1e-6");\n'
          '    model.component("comp1").geom("geom1")'
          '.feature("selPipes").set("condition", "inside");\n')
    return s


def _pipes_physics(P, dim):
    if not P.get("n_pipes"):
        return ""
    return (f'    model.component("comp1").physics("ht")'
            f'.create("hfp1",\n        "HeatFluxBoundary", '
            f'{dim - 1});\n'
            '    model.component("comp1").physics("ht")'
            '.feature("hfp1")\n'
            '        .selection().named("geom1_selPipes");\n'
            '    model.component("comp1").physics("ht")'
            '.feature("hfp1")\n'
            '        .set("HeatFluxType", '
            '"ConvectiveHeatFlux");\n'
            '    model.component("comp1").physics("ht")'
            '.feature("hfp1").set("h", "h_w");\n'
            '    model.component("comp1").physics("ht")'
            '.feature("hfp1").set("Text", "T_w");\n')


def _pipes_cpl(P, dim):
    if not P.get("n_pipes"):
        return ""
    return ('    model.component("comp1").cpl().create("intPipe", '
            '"Integration");\n'
            '    model.component("comp1").cpl("intPipe")'
            f'.selection().geom("geom1", {dim - 1});\n'
            '    model.component("comp1").cpl("intPipe")'
            '.selection()\n        .named("geom1_selPipes");\n'
            '    model.component("comp1").cpl().create("intBot", '
            '"Integration");\n'
            '    model.component("comp1").cpl("intBot")'
            f'.selection().geom("geom1", {dim - 1});\n'
            '    model.component("comp1").cpl("intBot")'
            '.selection()\n        .named("geom1_selBot");\n')


def _eval_rows(P, dim, top_fixed, fan):
    """(expr, unit, desc) rows per configuration, pipes included."""
    per = "" if dim == 3 else "/L_z"
    U = "W" if dim == 3 else "W/m"
    pipes = bool(P.get("n_pipes"))
    rows = []
    if fan:
        adv = ("rho_oil*cp_oil*u_fan*W_tank"
               + ("*L_z" if dim == 3 else "")
               + "*(aveTop(T) - T_in)")
        rows += [("aveTop(T)", "degC", "FEA outlet mean T"),
                 ("Tout_pred", "degC",
                  "closed-form outlet mean"
                  + (" (no-pipe reference)" if pipes else
                     " (the anchor)")),
                 ("aveTop(T) - Tout_pred", "K",
                  "deviation from the no-pipe closed form"
                  if pipes else "DEVIATION - must be ~0"),
                 ("maxB(T)", "degC", "bar peak T"),
                 (adv, U, "advected out of the top")]
        if pipes:
            rows += [("intPipe(ht.ntflux)", U,
                      "heat into the water pipes"),
                     ("intBot(ht.ntflux)", U,
                      "conductive leak out of the inlet"),
                     (f"Q_cell{per} - ({adv}) - "
                      "intPipe(ht.ntflux) - intBot(ht.ntflux)",
                      U, "BALANCE - must be ~0")]
        else:
            rows += [(f"Q_cell{per}", U,
                      "bar heat (advected + inlet leak = this)")]
    elif top_fixed:
        rows += [("maxB(T)", "degC", "bar peak T"),
                 ("aveB(T)", "degC", "bar average T"),
                 ("aveAll(T)", "degC",
                  "tank volume-average T"),
                 ("intTop(ht.ntflux)", U,
                  "heat out of the fixed top")]
        if pipes:
            rows += [("intPipe(ht.ntflux)", U,
                      "heat into the water pipes"),
                     (f"intTop(ht.ntflux) + intPipe(ht.ntflux)"
                      f" - Q_cell{per}", U,
                      "BALANCE - must be ~0")]
        else:
            rows += [(f"Q_cell{per}", U,
                      "bar heat (the anchor)"),
                     (f"intTop(ht.ntflux) - Q_cell{per}", U,
                      "DEVIATION - must be ~0 at the solution")]
    else:
        rows += [("aveAll(T)", "degC", "FEA volume-average T"),
                 ("T0_C + dTdt_pred*t", "degC",
                  "exact adiabatic line (the anchor)"),
                 ("aveAll(T) - (T0_C + dTdt_pred*t)", "K",
                  "DEVIATION - must be ~0 (sealed)"),
                 ("maxB(T)", "degC", "bar peak T"),
                 ("aveB(T)", "degC", "bar average T")]
    return rows


def _eval_java(rows):
    e = ", ".join(f'"{r[0]}"' for r in rows)
    u = ", ".join(f'"{r[1]}"' for r in rows)
    d = ", ".join(f'"{r[2]}"' for r in rows)
    return (f'    model.result().numerical().create("gev1", '
            f'"EvalGlobal");\n'
            f'    model.result().numerical("gev1").set("expr", '
            f'new String[]{{\n        {e}}});\n'
            f'    model.result().numerical("gev1").set("unit", '
            f'new String[]{{\n        {u}}});\n'
            f'    model.result().numerical("gev1").set("descr", '
            f'new String[]{{\n        {d}}});\n')


def _qcell_rows(P):
    if P.get("heat_mode") == "battery":
        return [
            ("I_cell", f"{P.get('I_cell', 5.0)}[A]",
             "battery constant current - sweep me in COMSOL"),
            ("R0_cell", f"{P.get('R0_cell', 0.02)}[ohm]",
             "battery ohmic resistance at the set SOC (from the "
             "model card)"),
            ("R1_cell", f"{P.get('R1_cell', 0.01)}[ohm]",
             "battery polarisation resistance at the set SOC"),
            ("Q_cell", "I_cell^2*(R0_cell + R1_cell)",
             "total bar heat FROM THE BATTERY MODEL"),
        ]
    return [("Q_cell", f"{P['Q_cell']}[W]", "total bar heat")]

def comsol_basic_2d(P):
    """P keys: W_tank, H_tank, a_cell, x_off, gap_bot, L_z, Q_cell,
    k_bat, rho_bat, cp_bat, k_oil, rho_oil, cp_oil, T0, t_end,
    t_step, dTdt_pred, oil_name, bar_name, top_fixed (bool),
    T_top, k_mult, steady (bool), cls (class/file name)."""
    cls = P.get("cls", "ipl2d")
    top_fixed = bool(P.get("top_fixed", True))
    fan = P.get("flow_mode", "") == "fan"
    if fan:
        top_fixed = False
    steady = bool(P.get("steady", top_fixed or fan))
    build_only = bool(P.get("build_only", False))
    s = f"""/*
 * BASIC MODULE - a heat bar in a liquid tank (plane 2D), matched to
 * the ODYSSEV-WP3 Fluent report.
 * {DISCLAIMER}
 *
 * Geometry: tank {P['W_tank']*1000:.0f} x {P['H_tank']*1000:.0f} mm;
 * bar ({P['bar_name']}) square {P['a_cell']*1000:.1f} mm, x offset
 * {P['x_off']*1000:.0f} mm, {P['gap_bot']*1000:.0f} mm above the
 * floor. Depth {P['L_z']*1000:.0f} mm converts the bar's total
 * {P['Q_cell']:.3f} W to q_v = {P['Q_cell']/(P['a_cell']**2*P['L_z']):.3g} W/m3
 * (the report uses 1e5). Liquid: {P['oil_name']}, effective-k
 * multiplier k_mult = {P.get('k_mult',1.0):.2f} (1 = pure conduction;
 * the value that reproduces Fluent's field IS the Nusselt number of
 * the buoyant circulation Fluent resolves and this model does not).
 *
 * Boundary conditions: sides and bottom adiabatic; top {'FIXED at T_top (the report sink) - a steady state exists' if top_fixed else 'ADIABATIC (sealed) - transient only'}.
 * Study: {'Stationary' if steady else 'Transient'}.
 * BUILT-IN CHECKS: {'at the solution, the heat leaving the top must equal the bar heat per metre, Q_cell/L_z - the Evaluation Group prints both and the deviation.' if top_fixed else 'sealed and adiabatic, the volume-average T must rise at exactly dTdt_pred = %.4f K/min; the Evaluation Group prints the deviation at every time - it must sit at numerical zero.' % (P['dTdt_pred']*60)}
 *
 * Run - TWO STEPS. COMSOL 6.x batch accepts .mph or a compiled
 * .class, NOT raw .java (per the COMSOL commands reference), so
 * compile first, then run:
 * macOS:
 *   /Applications/COMSOL64/Multiphysics/bin/comsol compile {cls}.java
 *   /Applications/COMSOL64/Multiphysics/bin/comsol batch -inputfile {cls}.class
 *   (adjust COMSOL64 to your version: ls /Applications | grep COMSOL)
 * Windows: bin/win64/comsolcompile.exe {cls}.java  then
 *          bin/win64/comsolbatch.exe -inputfile {cls}.class
 * Linux:   comsol compile {cls}.java && comsol batch -inputfile {cls}.class
 * GUI alternative after compiling: COMSOL Desktop > File > Open,
 * file type "Compiled Model File for Java (*.class)".
 * Either way COMSOL compiles with its bundled Java,
 * Saves {cls}.mph and writes {cls}_summary.txt.
 * COMSOL 6.x Java API, heat transfer in solids only.
 */
import com.comsol.model.*;
import com.comsol.model.util.*;
import java.io.IOException;

public class {cls} {{
  public static Model run() throws IOException {{
    Model model = ModelUtil.create("Model");
"""
    prm = [
        ("W_tank", f"{P['W_tank']}[m]", "tank inner width"),
        ("H_tank", f"{P['H_tank']}[m]", "tank inner height"),
        ("b_w", f"{P.get('b_w', P['a_cell'])}[m]",
         "bar width (x) - one cell diameter in battery-row mode"),
        ("b_h", f"{P.get('b_h', P['a_cell'])}[m]",
         "bar height - the cell height in battery-row mode"),
        ("n_rows_", f"{int(P.get('n_rows', 1) or 1)}",
         "number of battery rows across the width"),
        ("pitch_x", f"{P.get('pitch_x', 0.025)}[m]",
         "row centre-to-centre spacing across the width"),
        ("W_bars", "n_rows_*b_w",
         "total heated width (all rows)"),
        ("x_off", f"{P['x_off']}[m]",
         "battery centre offset from tank centreline"),
        ("gap_bot", f"{P['gap_bot']}[m]",
         "battery bottom above the tank floor"),
        ("L_z", f"{P['L_z']}[m]", "depth into the plane (for Q only)"),
                *_qcell_rows(P),
        ("q_v", "Q_cell/(W_bars*b_h*L_z)", "volumetric heat in the "
         "battery"),
        ("k_bat", f"{P['k_bat']}[W/(m*K)]",
         "battery in-plane conductivity"),
        ("rho_bat", f"{P['rho_bat']}[kg/m^3]", "battery density"),
        ("cp_bat", f"{P['cp_bat']}[J/(kg*K)]",
         "battery specific heat"),
        ("k_oil", f"{P['k_oil']}[W/(m*K)]",
         f"liquid conductivity ({P['oil_name']})"),
        ("rho_oil", f"{P['rho_oil']}[kg/m^3]", "liquid density"),
        ("cp_oil", f"{P['cp_oil']}[J/(kg*K)]",
         "liquid specific heat"),
        ("T0_C", f"{P['T0']}[degC]", "initial temperature"),
        ("t_end", f"{P['t_end']}[s]", "simulated time"),
        ("t_step", f"{P['t_step']}[s]", "output interval"),
        ("T_top", f"{P.get('T_top', 25.0)}[degC]",
         "top-face temperature (the report's sink)"),
        ("k_mult", f"{P.get('k_mult', 1.0)}",
         "liquid effective-k multiplier; 1 = pure conduction, the "
         "CFD-matching value = Nu of the buoyant circulation"),
        ("u_fan", f"{P.get('u_fan', 0.0005)}[m/s]",
         "fan mode: prescribed upward oil speed"),
        ("T_in", f"{P.get('T_in', 25.0)}[degC]",
         "fan mode: inlet oil temperature at the floor"),
        ("P_adv", "rho_oil*cp_oil*u_fan/(k_mult*k_oil)",
         "fan mode: advection parameter [1/m]"),
        ("m_slope", "q_v*W_bars/W_tank/(rho_oil*cp_oil*u_fan)",
         "fan mode: mean-profile slope in the bar band"),
        ("Tout_pred",
         "T_in + m_slope*b_h + (m_slope/P_adv)*"
         "(exp(-P_adv*(gap_bot+b_h)) - exp(-P_adv*gap_bot))",
         "fan mode: EXACT outlet mean temperature (the anchor)"),
        *_pipe_prm_rows(P),
        ("A_cell", "W_bars*b_h", "battery cross-section, all rows"),
        ("A_oil", "W_tank*H_tank - W_bars*b_h", "liquid cross-section"),
        ("dTdt_pred",
         "Q_cell/L_z/(rho_bat*cp_bat*A_cell + rho_oil*cp_oil*A_oil)",
         "exact adiabatic heating slope - the correctness anchor"),
    ]
    for k, v, dsc in prm:
        s += f'    model.param().set("{k}", "{v}", "{dsc}");\n'
    topbc = ("    // the report's sink: top face held at T_top\n"
             "    model.component(\"comp1\").physics(\"ht\")"
             ".create(\"temp1\", \"TemperatureBoundary\", 1);\n"
             "    model.component(\"comp1\").physics(\"ht\")"
             ".feature(\"temp1\").selection()"
             ".named(\"geom1_selTop\");\n"
             "    model.component(\"comp1\").physics(\"ht\")"
             ".feature(\"temp1\").set(\"T0\", \"T_top\");\n"
             if top_fixed else
             "    // no fixed-temperature lid in this configuration\n"
             if fan else
             "    // sealed: no boundary features - COMSOL's default"
             " is thermal insulation everywhere\n")
    fanblk = ""
    if fan:
        fanblk = (
            "    // FAN MODE: the liquid advects upward at u_fan.\n"
            "    // Prescribed velocity on the Fluid feature; if "
            "your COMSOL version\n"
            "    // stores the velocity as a model input instead, "
            "swap the marked line\n"
            "    // for the commented alternative below it.\n"
            '    model.component("comp1").physics("ht")'
            '.create("fld1",\n'
            '        "FluidHeatTransferModel", 2);\n'
            '    model.component("comp1").physics("ht")'
            '.feature("fld1")\n'
            '        .selection().named("geom1_selOil");\n'
            '    model.component("comp1").physics("ht")'
            '.feature("fld1")\n'
            '        .set("u", new String[]{"0", "u_fan", "0"});'
            '   // primary API\n'
            '    // model.component("comp1").physics("ht")'
            '.feature("fld1")\n'
            '    //     .set("minput_velocity", new String[]{"0", "u_fan", "0"});\n'
            '    model.component("comp1").physics("ht")'
            '.create("tin1",\n'
            '        "TemperatureBoundary", 1);\n'
            '    model.component("comp1").physics("ht")'
            '.feature("tin1")\n'
            '        .selection().named("geom1_selBot");\n'
            '    model.component("comp1").physics("ht")'
            '.feature("tin1")\n'
            '        .set("T0", "T_in");\n'
            '    // ht outflow node: API ID is ConvectiveOutflow (the plain\n'
            '    // "Outflow" ID belongs to other interfaces)\n'
            '    model.component("comp1").physics("ht")'
            '.create("out1",\n'
            '        "ConvectiveOutflow", 1);\n'
            '    model.component("comp1").physics("ht")'
            '.feature("out1")\n'
            '        .selection().named("geom1_selTop");\n')
    _run = ("" if build_only else
            "    model.study(\"std1\").run();\n")
    if steady:
        study = ("    model.study().create(\"std1\");\n"
                 "    model.study(\"std1\").create(\"stat\","
                 " \"Stationary\");\n" + _run)
    else:
        study = ("    model.study().create(\"std1\");\n"
                 "    model.study(\"std1\").create(\"time\","
                 " \"Transient\");\n"
                 "    model.study(\"std1\").feature(\"time\")\n"
                 "        .set(\"tlist\","
                 " \"range(0,t_step,t_end)\");\n" + _run)
    if build_only:
        study += ("    // BUILD-ONLY: open the saved .mph in the "
                  "Desktop and press Compute (F8);\n"
                  "    // then Results > Derived Values > Evaluate "
                  "All fills the table, and the\n"
                  "    // plot groups render.\n")
    evals = _eval_java(_eval_rows(P, 2, top_fixed, fan))
    pg2 = ("" if steady else
           """    model.result().create("pg2", "PlotGroup1D");
    model.result("pg2").create("glob1", "Global");
    model.result("pg2").feature("glob1").set("expr", new String[]{
        "aveAll(T)", "T0_C + dTdt_pred*t"});
    model.result("pg2").feature("glob1").set("unit", new String[]{
        "degC", "degC"});
""")
    s += """
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 2);
    // the tank
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1")
        .set("size", new String[]{"W_tank", "H_tank"});
__ROWS2D____PIPEGEOM__    // named selection tightly around the battery domain
    model.component("comp1").geom("geom1").create("selCell",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("entitydim", 2);
    model.component("comp1").geom("geom1").feature("selCell")
        .set("xmin", "W_tank/2 + x_off - (n_rows_-1)/2.0*pitch_x - b_w/2 - 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("xmax", "W_tank/2 + x_off + (n_rows_-1)/2.0*pitch_x + b_w/2 + 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("ymin", "gap_bot - 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("ymax", "gap_bot + b_h + 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("condition", "inside");
    // the top face, for the fixed-temperature sink and its flux check
    model.component("comp1").geom("geom1").create("selTop",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("selTop")
        .set("xmin", "-1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("xmax", "W_tank + 1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("ymin", "H_tank - 1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("ymax", "H_tank + 1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("condition", "inside");
    model.component("comp1").geom("geom1").create("selBot",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("selBot")
        .set("ymin", "-1e-6");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("ymax", "1e-6");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("condition", "inside");
    model.component("comp1").geom("geom1").create("selOil",
        "ComplementSelection");
    model.component("comp1").geom("geom1").feature("selOil")
        .set("entitydim", 2);
    model.component("comp1").geom("geom1").feature("selOil")
        .set("input", new String[]{"selCell"});
    model.component("comp1").geom("geom1").run();

    // liquid everywhere, battery material overriding its own domain
    model.component("comp1").material().create("matOil", "Common");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("thermalconductivity", "k_mult*k_oil");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("density", "rho_oil");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("heatcapacity", "cp_oil");
    model.component("comp1").material("matOil").selection().all();
    model.component("comp1").material().create("matBat", "Common");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("thermalconductivity", "k_bat");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("density", "rho_bat");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("heatcapacity", "cp_bat");
    model.component("comp1").material("matBat").selection()
        .named("geom1_selCell");

    model.component("comp1").physics().create("ht", "HeatTransfer",
        "geom1");
    model.component("comp1").physics("ht").create("hs1", "HeatSource",
        2);
    model.component("comp1").physics("ht").feature("hs1").selection()
        .named("geom1_selCell");
    model.component("comp1").physics("ht").feature("hs1")
        .set("Q0", "q_v");
__TOPBC____FAN____PIPEPHY__    model.component("comp1").physics("ht").feature("init1")
        .set("Tinit", "T0_C");

    // operators for the checks
    model.component("comp1").cpl().create("aveAll", "Average");
    model.component("comp1").cpl("aveAll").selection().all();
    model.component("comp1").cpl().create("maxB", "Maximum");
    model.component("comp1").cpl("maxB").selection()
        .named("geom1_selCell");
    model.component("comp1").cpl().create("aveB", "Average");
    model.component("comp1").cpl("aveB").selection()
        .named("geom1_selCell");
    model.component("comp1").cpl().create("intTop", "Integration");
    model.component("comp1").cpl("intTop").selection()
        .geom("geom1", 1);
    model.component("comp1").cpl("intTop").selection()
        .named("geom1_selTop");
    model.component("comp1").cpl().create("aveTop", "Average");
    model.component("comp1").cpl("aveTop").selection()
        .geom("geom1", 1);
    model.component("comp1").cpl("aveTop").selection()
        .named("geom1_selTop");
__PIPECPL__
    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(3);

__STUDY__
__EVALS__    model.result().table().create("tbl1", "Table");
    model.result().numerical("gev1").set("table", "tbl1");
__EXEC__
    // surface + contour at the final time
    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", "T");
    model.result("pg1").feature("surf1").set("unit", "degC");
    model.result("pg1").create("con1", "Contour");
    model.result("pg1").feature("con1").set("expr", "T");
    model.result("pg1").feature("con1").set("unit", "degC");
__PG2__
__SETTINGS__    model.save("{cls}");
    return model;
  }

  public static void main(String[] args) throws IOException {
    run();
  }
}
"""
    _create = '\n'.join([
        '    model.result().export().create("texp1", "Table");',
        '    model.result().export("texp1").set("table", "tbl1");',
        '    model.result().export("texp1").set("filename",',
        '        "{cls}_summary.txt");',
        '    // full 2D temperature field on a regular grid - this is',
        '    // the file the app\'s "Check a COMSOL run" box reads',
        '    model.result().export().create("data1", "Data");',
        '    model.result().export("data1").set("expr",'
        ' new String[]{"T"});',
        '    model.result().export("data1").set("unit",'
        ' new String[]{"degC"});',
        '    model.result().export("data1").set("location",'
        ' "regulargrid");',
        '    model.result().export("data1").set("regulargridx2",'
        ' 61);',
        '    model.result().export("data1").set("regulargridy2",'
        ' 73);',
        '    model.result().export("data1").set("filename",',
        '        "{cls}_upload_to_app.txt");']) + '\n'
    _run = '\n'.join([
        '    model.result().numerical("gev1").setResult();',
        '    model.result().export("texp1").run();',
        '    model.result().export("data1").run();']) + '\n'
    execs = (_create +
             ("    // (after you press Compute: Evaluate All fills "
              "the table; right-click\n"
              "    // each Export node > Export to write the txt "
              "files)\n" if build_only else _run))
    s = (s.replace("__EXEC__", execs)
         .replace("__TOPBC__", topbc)
         .replace("__FAN__", fanblk)
         .replace("__ROWS2D__", _rows_geom_2d(P))
         .replace("__SETTINGS__",
                  _settings_java(dict(P, _dim=2), prm, cls))
         .replace("__PIPEGEOM__", _pipes_geom_2d(P))
         .replace("__PIPEPHY__", _pipes_physics(P, 2))
         .replace("__PIPECPL__", _pipes_cpl(P, 2))
         .replace("__STUDY__", study)
         .replace("__EVALS__", evals)
         .replace("__PG2__", pg2)
         .replace("{cls}", cls))
    return s


def comsol_basic_3d(P):
    """3D twin of the basic module: the same section extruded L_z in
    depth (the report's 25 x 30 x 300 mm tank with the 5 x 5 x 300 mm
    bar). Ends adiabatic, sides and bottom adiabatic, top FACE fixed
    at T_top (or sealed -> transient). Physics is z-invariant, so the
    2D analytical series is the EXACT solution here too and the 3D
    field must match the 2D field to solver tolerance - the exported
    4-column field lets the app measure that z-uniformity directly.
    Same P keys as comsol_basic_2d."""
    cls = P.get("cls", "ipl3d")
    top_fixed = bool(P.get("top_fixed", True))
    fan = P.get("flow_mode", "") == "fan"
    if fan:
        top_fixed = False
    steady = bool(P.get("steady", top_fixed or fan))
    build_only = bool(P.get("build_only", False))
    qv = P["Q_cell"] / (int(P.get("n_rows", 1) or 1) * P.get("b_w", P["a_cell"]) * P.get("b_h", P["a_cell"]) * P["L_z"])
    s = f"""/*
 * BASIC MODULE in 3D - the WP3 section extruded {P['L_z']*1000:.0f} mm.
 * {DISCLAIMER}
 *
 * Tank {P['W_tank']*1000:.0f} x {P['L_z']*1000:.0f} x {P['H_tank']*1000:.0f} mm (W x depth x H);
 * bar {P['a_cell']*1000:.1f} mm square x full depth, {P['gap_bot']*1000:.0f} mm
 * off the floor; q_v = {qv:.3g} W/m3 ({P['Q_cell']:.3f} W total).
 * BCs: {'FAN MODE - floor is the inlet at T_in, lid is the outflow, oil advects upward at u_fan; the exact outlet mean Tout_pred is tabulated with its deviation' if fan else "ends, sides and bottom adiabatic; top FACE " + ('fixed at T_top - steady state exists' if top_fixed else 'adiabatic (sealed) - transient only')}.
 *
 * PHYSICS NOTE: geometry and BCs are z-invariant, so the exact
 * solution is the 2D field at every depth. The app checks three
 * things from the exported field: z-uniformity (should be solver
 * noise), the mid-depth slice against the 2D analytical series, and
 * {'the total heat out of the top face against Q_cell (printed with its deviation below).' if top_fixed else 'the sealed adiabatic heating line for the volume average.'}
 *
 * Run (macOS):
 *   /Applications/COMSOL64/Multiphysics/bin/comsol compile {cls}.java
 *   /Applications/COMSOL64/Multiphysics/bin/comsol batch -inputfile {cls}.class
 * Exports {cls}_upload_to_app.txt (x y z T on a 61 x 21 x 73 grid) and
 * {cls}_summary.txt automatically{' after you press Compute (build-only file).' if build_only else '.'}
 */
import com.comsol.model.*;
import com.comsol.model.util.*;
import java.io.IOException;

public class {cls} {{
  public static Model run() throws IOException {{
    Model model = ModelUtil.create("Model");
"""
    prm = [
        ("W_tank", f"{P['W_tank']}[m]", "tank width (x)"),
        ("L_z", f"{P['L_z']}[m]", "tank depth (y)"),
        ("H_tank", f"{P['H_tank']}[m]", "tank height (z)"),
        ("b_w", f"{P.get('b_w', P['a_cell'])}[m]",
         "bar width (x)"),
        ("b_h", f"{P.get('b_h', P['a_cell'])}[m]",
         "bar height (z)"),
        ("n_rows_", f"{int(P.get('n_rows', 1) or 1)}",
         "cell columns across the width (x)"),
        ("n_cells_", f"{int(P.get('n_cells', 1) or 1)}",
         "cells along the depth (y)"),
        ("pitch_x", f"{P.get('pitch_x', 0.025)}[m]",
         "centre-to-centre spacing across the width"),
        ("pitch_y", f"{P.get('pitch_y', 0.025)}[m]",
         "centre-to-centre spacing along the depth"),
        ("n_tot_", "n_rows_*n_cells_", "total cell count"),
        ("W_bars", "n_rows_*b_w",
         "total heated width (all columns)"),
        ("V_bat",
         f"{'n_tot_*pi*(b_w/2)^2*b_h' if P.get('cyl_cells') else 'n_rows_*b_w*b_h*L_z'}",
         "total battery volume"),
        ("x_off", f"{P['x_off']}[m]", "bar offset from centreline"),
        ("gap_bot", f"{P['gap_bot']}[m]", "bar bottom above floor"),
        *_qcell_rows(P),
        ("q_v", "Q_cell/V_bat", "volumetric heat"),
        ("k_bat", f"{P['k_bat']}[W/(m*K)]", "bar conductivity"),
        ("rho_bat", f"{P['rho_bat']}[kg/m^3]", "bar density"),
        ("cp_bat", f"{P['cp_bat']}[J/(kg*K)]", "bar cp"),
        ("k_oil", f"{P['k_oil']}[W/(m*K)]",
         f"liquid conductivity ({P['oil_name']})"),
        ("rho_oil", f"{P['rho_oil']}[kg/m^3]", "liquid density"),
        ("cp_oil", f"{P['cp_oil']}[J/(kg*K)]", "liquid cp"),
        ("T0_C", f"{P['T0']}[degC]", "initial temperature"),
        ("t_end", f"{P['t_end']}[s]", "simulated time (transient)"),
        ("t_step", f"{P['t_step']}[s]", "output interval"),
        ("T_top", f"{P.get('T_top', 25.0)}[degC]", "top-face sink"),
        ("k_mult", f"{P.get('k_mult', 1.0)}",
         "liquid effective-k multiplier (CFD-matching value = Nu)"),
        ("u_fan", f"{P.get('u_fan', 0.0005)}[m/s]",
         "fan mode: prescribed upward oil speed"),
        ("T_in", f"{P.get('T_in', 25.0)}[degC]",
         "fan mode: inlet oil temperature at the floor"),
        ("P_adv", "rho_oil*cp_oil*u_fan/(k_mult*k_oil)",
         "fan mode: advection parameter [1/m]"),
        ("m_slope", "Q_cell/(b_h*W_tank*L_z)/(rho_oil*cp_oil*u_fan)",
         "fan mode: mean-profile slope in the bar band"),
        ("Tout_pred",
         "T_in + m_slope*b_h + (m_slope/P_adv)*"
         "(exp(-P_adv*(gap_bot+b_h)) - exp(-P_adv*gap_bot))",
         "fan mode: EXACT outlet mean temperature (the anchor)"),
        *_pipe_prm_rows(P),
        ("dTdt_pred",
         "Q_cell/(rho_bat*cp_bat*V_bat + "
         "rho_oil*cp_oil*(W_tank*H_tank*L_z - V_bat))",
         "exact sealed heating slope"),
    ]
    for k_, v_, d_ in prm:
        s += f'    model.param().set("{k_}", "{v_}", "{d_}");\n'
    s += """
    model.component().create("comp1", true);
    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").create("blk1", "Block");
    model.component("comp1").geom("geom1").feature("blk1")
        .set("size", new String[]{"W_tank", "L_z", "H_tank"});
""" + _rows_geom_3d(P) + """
""" + _pipes_geom_3d(P) + """    model.component("comp1").geom("geom1").create("selCell",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("entitydim", 3);
    model.component("comp1").geom("geom1").feature("selCell")
        .set("xmin", "W_tank/2 + x_off - (n_rows_-1)/2.0*pitch_x - b_w/2 - 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("xmax", "W_tank/2 + x_off + (n_rows_-1)/2.0*pitch_x + b_w/2 + 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("zmin", "gap_bot - 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("zmax", "gap_bot + b_h + 1e-6");
    model.component("comp1").geom("geom1").feature("selCell")
        .set("condition", "inside");
    model.component("comp1").geom("geom1").create("selTop",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("entitydim", 2);
    model.component("comp1").geom("geom1").feature("selTop")
        .set("zmin", "H_tank - 1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("zmax", "H_tank + 1e-6");
    model.component("comp1").geom("geom1").feature("selTop")
        .set("condition", "inside");
    model.component("comp1").geom("geom1").create("selBot",
        "BoxSelection");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("entitydim", 2);
    model.component("comp1").geom("geom1").feature("selBot")
        .set("zmin", "-1e-6");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("zmax", "1e-6");
    model.component("comp1").geom("geom1").feature("selBot")
        .set("condition", "inside");
    model.component("comp1").geom("geom1").create("selOil",
        "ComplementSelection");
    model.component("comp1").geom("geom1").feature("selOil")
        .set("entitydim", 3);
    model.component("comp1").geom("geom1").feature("selOil")
        .set("input", new String[]{"selCell"});
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("matOil", "Common");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("thermalconductivity", "k_mult*k_oil");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("density", "rho_oil");
    model.component("comp1").material("matOil").propertyGroup("def")
        .set("heatcapacity", "cp_oil");
    model.component("comp1").material("matOil").selection().all();
    model.component("comp1").material().create("matBat", "Common");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("thermalconductivity", "k_bat");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("density", "rho_bat");
    model.component("comp1").material("matBat").propertyGroup("def")
        .set("heatcapacity", "cp_bat");
    model.component("comp1").material("matBat").selection()
        .named("geom1_selCell");

    model.component("comp1").physics().create("ht", "HeatTransfer",
        "geom1");
    model.component("comp1").physics("ht").create("hs1", "HeatSource",
        3);
    model.component("comp1").physics("ht").feature("hs1").selection()
        .named("geom1_selCell");
    model.component("comp1").physics("ht").feature("hs1")
        .set("Q0", "q_v");
"""
    if fan:
        s += """    // FAN MODE: liquid advects upward at u_fan; inlet floor at
    // T_in; outflow lid. Velocity on the Fluid feature - commented
    // fallback below if your version uses the model-input form.
    model.component("comp1").physics("ht").create("fld1",
        "FluidHeatTransferModel", 3);
    model.component("comp1").physics("ht").feature("fld1")
        .selection().named("geom1_selOil");
    model.component("comp1").physics("ht").feature("fld1")
        .set("u", new String[]{"0", "0", "u_fan"});   // primary API
    // model.component("comp1").physics("ht").feature("fld1")
    //     .set("minput_velocity", new String[]{"0","0","u_fan"});
    model.component("comp1").physics("ht").create("tin1",
        "TemperatureBoundary", 2);
    model.component("comp1").physics("ht").feature("tin1")
        .selection().named("geom1_selBot");
    model.component("comp1").physics("ht").feature("tin1")
        .set("T0", "T_in");
    model.component("comp1").physics("ht").create("out1",
        "ConvectiveOutflow", 2);
    model.component("comp1").physics("ht").feature("out1")
        .selection().named("geom1_selTop");
"""
    if top_fixed:
        s += """    model.component("comp1").physics("ht").create("temp1",
        "TemperatureBoundary", 2);
    model.component("comp1").physics("ht").feature("temp1")
        .selection().named("geom1_selTop");
    model.component("comp1").physics("ht").feature("temp1")
        .set("T0", "T_top");
"""
    s += _pipes_physics(P, 3)
    s += """    model.component("comp1").physics("ht").feature("init1")
        .set("Tinit", "T0_C");

    model.component("comp1").cpl().create("aveAll", "Average");
    model.component("comp1").cpl("aveAll").selection().all();
    model.component("comp1").cpl().create("maxB", "Maximum");
    model.component("comp1").cpl("maxB").selection()
        .named("geom1_selCell");
    model.component("comp1").cpl().create("aveB", "Average");
    model.component("comp1").cpl("aveB").selection()
        .named("geom1_selCell");
    model.component("comp1").cpl().create("intTop", "Integration");
    model.component("comp1").cpl("intTop").selection()
        .geom("geom1", 2);
    model.component("comp1").cpl("intTop").selection()
        .named("geom1_selTop");
    model.component("comp1").cpl().create("aveTop", "Average");
    model.component("comp1").cpl("aveTop").selection()
        .geom("geom1", 2);
    model.component("comp1").cpl("aveTop").selection()
        .named("geom1_selTop");
""" + _pipes_cpl(P, 3) + """

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(4);

"""
    if steady:
        s += ('    model.study().create("std1");\n'
              '    model.study("std1").create("stat", '
              '"Stationary");\n')
    else:
        s += ('    model.study().create("std1");\n'
              '    model.study("std1").create("time", '
              '"Transient");\n'
              '    model.study("std1").feature("time")\n'
              '        .set("tlist", "range(0,t_step,t_end)");\n')
    if not build_only:
        s += '    model.study("std1").run();\n'
    else:
        s += ('    // BUILD-ONLY: open the .mph, press Compute (F8);'
              ' then Evaluate All\n    // and right-click each'
              ' Export node > Export.\n')
    evals = _eval_java(_eval_rows(P, 3, top_fixed, fan))
    s += evals + f"""
    model.result().table().create("tbl1", "Table");
    model.result().numerical("gev1").set("table", "tbl1");
    model.result().export().create("texp1", "Table");
    model.result().export("texp1").set("table", "tbl1");
    model.result().export("texp1").set("filename",
        "{cls}_summary.txt");
    model.result().export().create("data1", "Data");
    model.result().export("data1").set("expr", new String[]{{"T"}});
    model.result().export("data1").set("unit",
        new String[]{{"degC"}});
    model.result().export("data1").set("location", "regulargrid");
    model.result().export("data1").set("regulargridx3", 61);
    model.result().export("data1").set("regulargridy3", 21);
    model.result().export("data1").set("regulargridz3", 73);
    model.result().export("data1").set("filename",
        "{cls}_upload_to_app.txt");
"""
    if not build_only:
        s += ('    model.result().numerical("gev1").setResult();\n'
              '    model.result().export("texp1").run();\n'
              '    model.result().export("data1").run();\n')
    s += f"""
    model.result().create("pg1", "PlotGroup3D");
    model.result("pg1").create("vol1", "Volume");
    model.result("pg1").feature("vol1").set("expr", "T");
    model.result("pg1").feature("vol1").set("unit", "degC");

{_settings_java(dict(P, _dim=3), prm, cls)}    model.save("{cls}");
    return model;
  }}

  public static void main(String[] args) throws IOException {{
    run();
  }}
}}
"""
    return s
